import React, { useMemo } from 'react';
import { Question } from '../types';
import { QuestionCard } from './QuestionCard';
import { Download, Printer } from 'lucide-react';

interface ExamPaperProps {
  questions: Question[];
}

export const ExamPaper: React.FC<ExamPaperProps> = ({ questions }) => {
  // 1. Group by Topic
  // 2. Sort by Difficulty inside Topic
  const structuredData = useMemo(() => {
    const groups: Record<string, Question[]> = {};
    
    questions.forEach(q => {
      if (!groups[q.topic]) {
        groups[q.topic] = [];
      }
      groups[q.topic].push(q);
    });

    // Sort questions within groups by difficulty
    Object.keys(groups).forEach(topic => {
      groups[topic].sort((a, b) => a.difficulty - b.difficulty);
    });

    // Sort topics alphabetically (optional, but good for consistency)
    return Object.entries(groups).sort((a, b) => a[0].localeCompare(b[0]));
  }, [questions]);

  const handlePrint = () => {
    window.print();
  };

  if (questions.length === 0) {
    return null;
  }

  return (
    <div className="bg-white shadow-xl rounded-none sm:rounded-lg max-w-4xl mx-auto overflow-hidden print:shadow-none print:w-full print:max-w-none">
      {/* Paper Header / Toolbar */}
      <div className="bg-slate-800 text-white p-4 flex justify-between items-center print:hidden">
        <h2 className="font-medium">Print Preview</h2>
        <div className="flex gap-2">
           <button 
            onClick={handlePrint}
            className="flex items-center gap-2 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 rounded text-sm transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / Save PDF
          </button>
        </div>
      </div>

      {/* Actual Paper Content */}
      <div className="p-8 sm:p-12 min-h-[29.7cm] bg-white text-black print:p-0">
        
        <div className="text-center mb-12 border-b-2 border-black pb-4">
          <h1 className="text-3xl font-bold uppercase tracking-widest font-serif mb-2">Question Paper</h1>
          <p className="text-sm font-sans text-slate-500">Generated by ExamForge AI</p>
        </div>

        {structuredData.map(([topic, topicQuestions]) => (
          <div key={topic} className="mb-8 break-inside-avoid">
            <div className="border-b border-slate-300 pb-1 mb-4">
               <h3 className="text-xl font-bold font-serif text-slate-800">{topic}</h3>
               <p className="text-xs italic text-slate-500 font-sans">
                 (Questions sorted from Easy to Hard)
               </p>
            </div>
            
            <div className="space-y-4">
              {topicQuestions.map((q, idx) => (
                <QuestionCard 
                  key={`${topic}-${idx}`} 
                  question={q} 
                  index={idx + 1} // Logic could be adjusted to be continuous across paper if desired, but typically restarts or continues. Let's restart for topic or keep simple index. Let's use simple index.
                />
              ))}
            </div>
            
            <hr className="my-8 border-slate-200 border-dashed print:hidden" />
          </div>
        ))}
        
        <div className="mt-16 text-center text-xs text-slate-400 font-mono print:hidden">
          --- End of Document ---
        </div>
      </div>
    </div>
  );
};
